import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "src/utils/api";

const Home: NextPage = () => {


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center gap-6">
        <div className="bg-primary rounded-xl p-6 gap-3 flex flex-col shadow-md">
          <h1 className="text-3xl text-center text-white font-semibold">Calendar</h1>
          <div className="gap-3 grid grid-cols-7">

            {
              Array.from(Array(31).keys()).map((x) => {
                return <div className="rounded-full text-primary bg-white h-8 w-8 flex justify-center items-center" key={x}>
                  {x + 1}
                </div>
              })
            }
          </div>
        </div>
        <Link href={'/chat'} className="btn btn-primary">Daily Journal</Link>
      </main>
    </>
  );
};

export default Home;


