import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "src/utils/api";

const Home: NextPage = () => {


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center gap-6">
        <div className="bg-primary rounded-xl p-6 gap-3 flex flex-col shadow-md">
          <h1 className="text-3xl text-center p-3 text-white font-semibold">{`Today's Mood`}</h1>
          <div className="grid grid-cols-5 gap-3 w-fit justify-center">
            {
              Array.from(Array(5).keys()).map((x) => {
                return <div className="rounded-full text-primary bg-white h-8 w-8 flex justify-center items-center" key={x}>
                  {x}
                </div>
              })
            }
          </div>
        </div>
        <div className="bg-slate-50 rounded-md py-16">
          <div className="chat chat-start">
            <div className="chat-bubble">{`It's over Anakin,`} <br />I have the high ground.</div>
          </div>
          <div className="chat chat-end">
            <div className="chat-bubble">You underestimate my power!</div>
          </div>
          <div className="chat chat-end">
            <div className="chat-bubble">You underestimate my power!</div>
          </div>
        </div>
        <button className="btn">Ask me a question</button>
        <button className="btn">Save</button>
      </main>

    </>
  );
};

export default Home;


