import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";


import { api } from "src/utils/api";
import Calendar from "src/components/calendar";
import { useEffect, useState } from "react";
import dayjs from "dayjs";
import { CgSpinner } from 'react-icons/cg'
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const router = useRouter();

  const { data: sessionData, status: sessionStatus } = useSession();

  const { data: diaryData, refetch: refetchDiary } =
    api.diary.getMyDiaries.useQuery(
      undefined, // no input
      { enabled: sessionData?.user !== undefined }
    );

  const [selectedDay, setSelectedDay] = useState<Date>()
  const [diary, setDiary] = useState<{ title: string, content: string, id: string }[]>([])
  const moods: { [key: string]: "happy" | "sad" } = {
    "2023/04/02": "happy",
    "2023/04/01": "sad"
  }
  useEffect(() => {
    if (selectedDay && diaryData) {
      setDiary(diaryData.filter((data) => {
        console.log(dayjs(selectedDay))
        console.log(dayjs(data.createdAt))
        console.log(dayjs(selectedDay).isSame(dayjs(data.createdAt), "day"))
        return dayjs(selectedDay).isSame(dayjs(data.createdAt), "day")
      }).map((data) => {
        return {
          title: data.title,
          content: data.content,
          id: data.id
        }
      }))

    }
  }, [selectedDay, diaryData])

  useEffect(() => {
    console.log(diaryData)
  }, [diaryData])

  if (sessionStatus === 'loading') {
    return <div className="w-screen h-screen flex justify-center items-center">
      <CgSpinner size={32} className="animate-spin" />
    </div>
  }
  else if (sessionStatus === 'unauthenticated') {
    return <div className="w-screen h-screen flex flex-col gap-3 justify-center items-center">
      <div className="flex flex-col justify-center items-center">
        <h1 className="text-white text-4xl font-bold">APP NAME</h1>
        <h1 className="text-white text-lg">description...</h1>
      </div>
      <button className="btn" onClick={() => { void signIn() }}>
        Sign In
      </button>
    </div>
  }
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen py-16 flex-col items-center justify-center">
        <main className="flex flex-col justify-center items-center max-w-3xl mx-auto gap-6">
          <div className="flex flex-col justify-center items-center">
            <h1 className="text-white text-4xl font-bold">APP NAME</h1>
            <h1 className="text-white text-lg">description...</h1>
          </div>
          <Calendar moods={moods} onClick={(val) => {
            setSelectedDay(val)
          }} />
          <div className="flex flex-col gap-3">
            {diary && diary.length > 0 ?
              diary.map((currentDiary, idx) => {
                return <div className="w-72  bg-white hover:bg-gray-200 hover:cursor-pointer transition-colors rounded-md p-3"
                  key={currentDiary.id}
                  onClick={() => {
                    void router.push(`/diary/${currentDiary.id}`);
                  }}>
                  <h1 className="font-bold text-primary">{currentDiary.title}</h1>
                  <p>{currentDiary.content}</p>
                </div>
              }) :
              <div className="w-72 h-20 bg-white rounded-md p-3 flex justify-center items-center">
                <h1 className="text-error"> Oops! No diary on this day</h1>

              </div>
            }

          </div>
          <Link href={'/diary'} className="btn btn-primary">Write A Diary!</Link>
          <Link href={'/chat'} className="btn btn-primary">Chat with yourself</Link>
        </main>

      </div>
    </>
  );
};

export default Home;


