import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import Container from "src/components/Container";
import Nav from "src/components/Nav";
import { BsArchiveFill, BsArchive } from "react-icons/bs";
import { api } from "src/utils/api";

const DiaryPage: NextPage = () => {
  const { data: sessionData } = useSession();
  const { data: diaryData, refetch: refetchDiary } =
    api.diary.getMyDiaries.useQuery(
      undefined, // no input
      { enabled: sessionData?.user !== undefined }
    );
  const router = useRouter();

  const [loading, setLoading] = useState(false);

  const mutation = api.diary.createDiary.useMutation({
    onSuccess: async (_) => {
      await refetchDiary();
      setLoading(false);
      return 'Dude'
    },
    onError: (e) => {
      console.error(e);
    },
  });

  return (
    <Container>
      <Head>
        <title>Diary</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav
        breads={[
          { title: "Home", path: "/" },
          { title: "Diary", path: "/diary" },
        ]}
      />
      <main className="flex min-h-screen w-full flex-col items-center ">
        <div className="w-full">
          <table className="table-compact table w-full">
            <thead>
              <tr>
                <th></th>
                <th>Date</th>
                <th>Title</th>
                <th className="">
                  <button
                    className={`btn-primary btn-sm btn ${loading ? 'loading' : ''}`}
                    onClick={() => {
                      if (loading) return;
                      setLoading(true);
                      void mutation.mutateAsync({
                        title: "Untitled",
                        content: "",
                      }).then((x) => {
                        console.log(x)
                      });
                    }}
                  >
                    {loading ? "Loading..." : "New"}
                  </button>
                </th>
              </tr>
            </thead>
            <tbody>
              {diaryData?.map((diary) => (
                <tr
                  key={diary.id}
                  className="hover cursor-pointer"
                  onClick={() => {
                    if (loading) return;
                    setLoading(true);
                    void router.push(`/diary/${diary.id}`);
                  }}
                >
                  <th className="">
                    {diary.isArchived ? <BsArchiveFill className="text-primary ml-2" /> : <BsArchive className="ml-2" />}
                  </th>
                  <td className="">
                    {Intl.DateTimeFormat("en-US").format(
                      new Date(diary.createdAt)
                    )}
                  </td>
                  <td className="">{diary.title}</td>
                  <td className=" truncate">{diary.content.length > 30 ? `${diary.content.slice(0, 30)}...` : diary.content}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </main>
    </Container>
  );
};

export default DiaryPage;
