import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "src/utils/api";

const DiaryPage: NextPage = () => {
  const { data } = api.diary.getMyDiary.useQuery();

  return (
    <>
      <Head>
        <title>Diary</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center">
        <div className="navbar px-4">
          <div className="logo navbar-start text-3xl font-semibold">Diary</div>
          <div className="navbar-end">
            <Link href="/diary/create">
              <button className="btn-primary btn">Create</button>
            </Link>
          </div>
        </div>
        <div className="w-full p-2">
          <table className="table w-full">
            <thead>
              <tr>
                <th>Date</th>
                <th>Title</th>
              </tr>
            </thead>
            <tbody>
              {data?.map((diary) => (
                <tr key={diary.id}>
                  <td>
                    {Intl.DateTimeFormat("en-US").format(
                      new Date(diary.createdAt)
                    )}
                  </td>
                  <td>{diary.title}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </main>
    </>
  );
};

export default DiaryPage;
